### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by alexhbnr**
Update mixEMT to Python3

### CODE REVIEW

**Comment by svohr** [comment]
@alexhbnr  Thanks for submitting this PR. I had been meaning to port this project to python 3 for a while, but hadn't got around to it yet, so this is great to see. I have a few changes to your branch I would like to add before merging. These include removing all references to python 2.7 and avoiding the utf-8 decoding by fetching the string directly using `pkg_resources`. If you enable "Allow edits from maintainers" on this PR, I can push my changes directly to your branch.

**Comment by alexhbnr** [comment]
Hi @svohr, yes, I did a quick and dirty job of changing only the parts that were necessary for me to get it running in Python3 but I realised that I missed a few Python2.7 references later. The option "Allow edits by maintainers" is enabled, so you should be able to submit to my branch, or did I miss something?

**Comment by svohr** [comment]
@alexhbnr Thanks, it turns out I had my own authentication confused. I pushed my changes. If they're OK with you, I'll go ahead and merge.

**Comment by alexhbnr** [comment]
Cool, all good with me! Please go ahead.

**Pull request merged**
